// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbYUgbR0tHaSfrujL8184AXYOCTP5W6NE',
    appId: '1:333409993687:web:04793729931ec56c554192',
    messagingSenderId: '333409993687',
    projectId: 'agritrade-bef87',
    authDomain: 'agritrade-bef87.firebaseapp.com',
    storageBucket: 'agritrade-bef87.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC13bvoWl1TDq7cd5yLj7tvKSxMq1rl64E',
    appId: '1:333409993687:android:a18324ec288fc026554192',
    messagingSenderId: '333409993687',
    projectId: 'agritrade-bef87',
    storageBucket: 'agritrade-bef87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChe_xK-Vm7Eo4X1d6DkYg0VWrTKpOw1R4',
    appId: '1:333409993687:ios:e436b1433d1b5251554192',
    messagingSenderId: '333409993687',
    projectId: 'agritrade-bef87',
    storageBucket: 'agritrade-bef87.firebasestorage.app',
    iosBundleId: 'com.example.agritrade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChe_xK-Vm7Eo4X1d6DkYg0VWrTKpOw1R4',
    appId: '1:333409993687:ios:e436b1433d1b5251554192',
    messagingSenderId: '333409993687',
    projectId: 'agritrade-bef87',
    storageBucket: 'agritrade-bef87.firebasestorage.app',
    iosBundleId: 'com.example.agritrade',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbYUgbR0tHaSfrujL8184AXYOCTP5W6NE',
    appId: '1:333409993687:web:258dc08a033cee77554192',
    messagingSenderId: '333409993687',
    projectId: 'agritrade-bef87',
    authDomain: 'agritrade-bef87.firebaseapp.com',
    storageBucket: 'agritrade-bef87.firebasestorage.app',
  );
}
